services:
  payment-db:
    image: postgres:16
    container_name: ficmart-payment-postgres

    environment:
      POSTGRES_DB: ficmart_payment_db
      POSTGRES_USER: ficmart_user
      POSTGRES_PASSWORD: ficmart_password

    ports:
      - "5433:5432"

    volumes:
      - ficmart-payment-data:/var/lib/postgresql/data

volumes:
  ficmart-payment-data: