spring.application.name=ficmart-payment-gateway

# Gateway database connection
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/ficmart_payment_db}
spring.datasource.username=${DB_USERNAME:ficmart_user}
spring.datasource.password=${DB_PASSWORD:ficmart_password}

# Flyway will manage our database schema, not Hibernate
spring.jpa.hibernate.ddl-auto=validate

# Mock bank is an external dependency, so its location must be configurable.
bank.base-url=${BANK_BASE_URL:http://localhost:8787}